# Generated by Django 4.0.2 on 2022-02-04 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
